POST http://localhost:8080/api/accounts
Content-Type: application/json

{
    "firstName": "Abebe3",
    "middleName": "Beso3",
    "lastName": "Bela3",
    "dateOfBirth": "1993-01-01",
    "phoneNumber": "+251911030303",
    "email": "abebe3@beso3.bela3",
    "pin": 33333
}

###
GET http://localhost:8080/api/accounts
