POST http://localhost:8080/api/accounts
Content-Type: application/json

{
    "firstName": "Abebe",
    "middleName": "Beso",
    "lastName": "Bela",
    "dateOfBirth": "1991-01-01",
    "phoneNumber": "+251911010101",
    "email": "abebe@beso.bela",
    "pin": 11111
}

###
GET http://localhost:8080/api/accounts
